### ISSUE TITLE
Responsabilidades Únicas

### ISSUE THREAD

**Issue by Lukasveiga** [danilofreiria/Econobotic-project#1]
Salve Danilo, primeiramente parabéns pelo projeto!

Uma ideia que eu queria te dar é se preocupar com a questão das múltiplas responsabilidades.

Tava olhando o teu controller e ele assume diversas responsabilidades: Consulta no  banco de dados, regras de negócio, validação e etc.

O ideal seria separar essas responsabilidades em camadas (pastas/arquivos js) e criar uma comunicação entre elas.

Assim o código ficaria mais legível e facilitaria mudanças futuras.

**Comment by danilofreiria** [comment]
Obrigado, Lukas! Então, eu pensei seriamente em fazer isso, principalmente no controlador de transações, quando chegou na 100° linha. Mas aí fiquei com a insegurança de criar muitos arquivos pra uma coisa só, e estragar tudo. Muito obrigado mesmo pelas dicas! Mas nesse caso, eu separaria apenas os controladores em arquivos separados, ou eu transformo as consultas sql em funções úteis? Eu tentei ao máximo não me repetir, mas inevitavelmente alguns blocos de código ficaram enormes

**Comment by Lukasveiga** [comment]
Um bom começo seria realmente separar as consultadas sql em funções como tu falou. Eu geralmente crio uma pasta repository e dentro um arquivo ou mais (depende de quantas entites o projeto tem) com as função, dai é só exportar para o controller.

Eu ainda crio uma camada service intermediária entre o controller e o repository, mas ai já vai de cada programador.

**Comment by danilofreiria** [comment]
Boa, vou pesquisar sobre isso! Obrigado mesmo!

**Comment by Lukasveiga** [comment]
Naada. Qualquer coisa me chama lá no discord já que somos da mesma turma na cubos kkk aí a gente dá uma refatorada nesse código!
